export default {
    // email
  email: /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+/,
    // phone
  phone: /^1(3|4|5|7|8)\d{9}$/,
    // 国内电话号码
  tel: /\d{3}-\d{8}|\d{4}-\d{7}/,
    // 身份证
  identityCard: /^\d{15}|\d{18}$/,
    // 短身份证号码(数字、字母x结尾)
  shortIdentityCard: /^([0-9]){7,18}(x|X)?$/,
    // 中国邮政编码(中国邮政编码为6位数字)
  postcode: /[1-9]\d{5}(?!\d)/,
    // 腾讯QQ号
  qqCheck: /[1-9][0-9]{4,}/,
    // 汉字
  chinese: /^[\u4e00-\u9fa5]{0,}$/,
    // 由数字和26个英文字母组成的字符串
  EnglishAndNumber: /^[A-Za-z0-9]+$/,
    // 由数字、26个英文字母或者下划线组成的字符串
  EnglishAndNumberAndUnderline: /^\w+$/,
    // 中文、英文、数字但不包括下划线等符号
  noUnderline: /^[\u4E00-\u9FA5A-Za-z0-9]+$/,
    // 密码(以字母开头，长度在6~18之间，只能包含字母、数字和下划线)
  password: /^[a-zA-Z]\w{5,17}$/,
    // 强密码(必须包含大小写字母和数字的组合，不能使用特殊字符，长度在8-10之间)
  strongPassword: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,10}$/,
    // 零和非零开头的数字
  normalNumber: /^(0|[1-9][0-9]*)$/,
    // 正数、负数、和小数
  dNumber: /^(\-|\+)?\d+(\.\d+)?$/,
    // 非零的正整数
  positiveIntegerExZero: /^[1-9]\d*$/,
    // 非零的负整数
  negativeIntegerExZero: /^-[1-9]\d*$/,
    // 可以输入含有^%&',;=?$\"等字符
  includeCharacter: /[^%&',;=?$\x22]+/,
    // xml文件
  xmlFile: /^([a-zA-Z]+-?)+[a-zA-Z0-9]+\\.[x|X][m|M][l|L]$/,
    // img图片
  imgRegExp: /image\/\w+/
}
